# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iPayBF' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iPayBF

  pod 'PopupDialog', '~> 1.1'

  target 'iPayBFTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iPayBFUITests' do
    # Pods for testing
  end


end

